In [1]:
import pandas as pd

In [3]:
# load and read the data
df = pd.read_csv('data/Philly_Unemployment.csv')

In [4]:
# how big is this data set? 408 rows and 60 columns
df.shape

(408, 60)

In [5]:
# preliminary view of data 
df.head()

,Geo_FIPS,Geo_QName,Geo_FILEID,Geo_STUSAB,Geo_SUMLEV,Geo_GEOCOMP,Geo_LOGRECNO,Geo_US,Geo_REGION,Geo_DIVISION,...,Geo_GEOID,Geo_NAME,Geo_BTTR,Geo_BTBG,Geo_PLACESE,SE_A17005_001,SE_A17005_002,SE_A17005_003,PCT_SE_A17005_002,PCT_SE_A17005_003
0,42101000101,"Census Tract 1.01, Philadelphia County, Pennsy...",ACSSF,pa,140,0,8807,NaN,NaN,NaN,...,14000US42101000101,Census Tract 1.01,NaN,NaN,NaN,1675,1590,85,94.93,5.07
1,42101000102,"Census Tract 1.02, Philadelphia County, Pennsy...",ACSSF,pa,140,0,8808,NaN,NaN,NaN,...,14000US42101000102,Census Tract 1.02,NaN,NaN,NaN,2246,2152,94,95.81,4.19
2,42101000200,"Census Tract 2, Philadelphia County, Pennsylvania",ACSSF,pa,140,0,8809,NaN,NaN,NaN,...,14000US42101000200,Census Tract 2,NaN,NaN,NaN,2361,2236,125,94.71,5.29
3,42101000300,"Census Tract 3, Philadelphia County, Pennsylvania",ACSSF,pa,140,0,8810,NaN,NaN,NaN,...,14000US42101000300,Census Tract 3,NaN,NaN,NaN,2097,2004,93,95.57,4.43
4,42101000401,"Census Tract 4.01, Philadelphia County, Pennsy...",ACSSF,pa,140,0,8811,NaN,NaN,NaN,...,14000US42101000401,Census Tract 4.01,NaN,NaN,NaN,1630,1622,8,99.51,0.49

In [9]:
#to see all columns and rows 
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [8]:
df.sample()

,Geo_FIPS,Geo_QName,Geo_FILEID,Geo_STUSAB,Geo_SUMLEV,Geo_GEOCOMP,Geo_LOGRECNO,Geo_US,Geo_REGION,Geo_DIVISION,Geo_STATECE,Geo_STATE,Geo_COUNTY,Geo_COUSUB,Geo_PLACE,Geo_TRACT,Geo_BLKGRP,Geo_CONCIT,Geo_AIANHH,Geo_AIANHHFP,Geo_AIHHTLI,Geo_AITSCE,Geo_AITS,Geo_ANRC,Geo_CBSA,Geo_CSA,Geo_METDIV,Geo_MACC,Geo_MEMI,Geo_NECTA,Geo_CNECTA,Geo_NECTADIV,Geo_UA,Geo_UACP,Geo_CDCURR,Geo_SLDU,Geo_SLDL,Geo_VTD,Geo_ZCTA3,Geo_ZCTA5,Geo_SUBMCD,Geo_SDELM,Geo_SDSEC,Geo_SDUNI,Geo_UR,Geo_PCI,Geo_TAZ,Geo_UGA,Geo_PUMA5,Geo_PUMA1,Geo_GEOID,Geo_NAME,Geo_BTTR,Geo_BTBG,Geo_PLACESE,SE_A17005_001,SE_A17005_002,SE_A17005_003,PCT_SE_A17005_002,PCT_SE_A17005_003
371,42101037700,"Census Tract 377, Philadelphia County, Pennsyl...",ACSSF,pa,140,0,9178,NaN,NaN,NaN,NaN,42,101,NaN,NaN,37700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14000US42101037700,Census Tract 377,NaN,NaN,NaN,2201,1771,430,80.46,19.54

In [10]:
# show data types
df.info(verbose = True,show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 408 entries, 0 to 407
Data columns (total 60 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Geo_FIPS           408 non-null    int64
 1   Geo_QName          408 non-null    object
 2   Geo_FILEID         408 non-null    object
 3   Geo_STUSAB         408 non-null    object
 4   Geo_SUMLEV         408 non-null    int64
 5   Geo_GEOCOMP        408 non-null    int64
 6   Geo_LOGRECNO       408 non-null    int64
 7   Geo_US             0 non-null      float64
 8   Geo_REGION         0 non-null      float64
 9   Geo_DIVISION       0 non-null      float64
 10  Geo_STATECE        0 non-null      float64
 11  Geo_STATE          408 non-null    int64
 12  Geo_COUNTY         408 non-null    int64
 13  Geo_COUSUB         0 non-null      float64
 14  Geo_PLACE          0 non-null      float64
 15  Geo_TRACT          408 non-null    int64
 16  Geo_BLKGRP         0 non-null      float64
 17  Geo_CONCIT         0 non-null      float64
 18  Geo_AIANHH         0 non-null      float64
 19  Geo_AIANHHFP       0 non-null      float64
 20  Geo_AIHHTLI        0 non-null      float64
 21  Geo_AITSCE         0 non-null      float64
 22  Geo_AITS           0 non-null      float64
 23  Geo_ANRC           0 non-null      float64
 24  Geo_CBSA           0 non-null      float64
 25  Geo_CSA            0 non-null      float64
 26  Geo_METDIV         0 non-null      float64
 27  Geo_MACC           0 non-null      float64
 28  Geo_MEMI           0 non-null      float64
 29  Geo_NECTA          0 non-null      float64
 30  Geo_CNECTA         0 non-null      float64
 31  Geo_NECTADIV       0 non-null      float64
 32  Geo_UA             0 non-null      float64
 33  Geo_UACP           0 non-null      float64
 34  Geo_CDCURR         0 non-null      float64
 35  Geo_SLDU           0 non-null      float64
 36  Geo_SLDL           0 non-null      float64
 37  Geo_VTD            0 non-null      float64
 38  Geo_ZCTA3          0 non-null      float64
 39  Geo_ZCTA5          0 non-null      float64
 40  Geo_SUBMCD         0 non-null      float64
 41  Geo_SDELM          0 non-null      float64
 42  Geo_SDSEC          0 non-null      float64
 43  Geo_SDUNI          0 non-null      float64
 44  Geo_UR             0 non-null      float64
 45  Geo_PCI            0 non-null      float64
 46  Geo_TAZ            0 non-null      float64
 47  Geo_UGA            0 non-null      float64
 48  Geo_PUMA5          0 non-null      float64
 49  Geo_PUMA1          0 non-null      float64
 50  Geo_GEOID          408 non-null    object
 51  Geo_NAME           408 non-null    object
 52  Geo_BTTR           0 non-null      float64
 53  Geo_BTBG           0 non-null      float64
 54  Geo_PLACESE        0 non-null      float64
 55  SE_A17005_001      408 non-null    int64
 56  SE_A17005_002      408 non-null    int64
 57  SE_A17005_003      408 non-null    int64
 58  PCT_SE_A17005_002  389 non-null    float64
 59  PCT_SE_A17005_003  389 non-null    float64
dtypes: float64(45), int64(10), object(5)
memory usage: 191.4+ KB

In [12]:
#look at FIPS data 
df.Geo_FIPS.head()

0    42101000101
1    42101000102
2    42101000200
3    42101000300
4    42101000401
Name: Geo_FIPS, dtype: int64

In [13]:
#look at state data
df.Geo_STATE.head()

0    42
1    42
2    42
3    42
4    42
Name: Geo_STATE, dtype: int64

In [14]:
#look at county 
df.Geo_COUNTY.head()

0    101
1    101
2    101
3    101
4    101
Name: Geo_COUNTY, dtype: int64

In [44]:
# reimport data and assign FIPS, STATE and COUNTY as string instead of int
df = pd.read_csv(
    'data/Philly_Unemployment.csv',
    dtype=
    {
        'Geo_FIPS':str,
        'Geo_STATE':str,
        'Geo_COUNTY': str
    }
)

In [45]:
#look at the data again
df.head()

,Geo_FIPS,Geo_QName,Geo_FILEID,Geo_STUSAB,Geo_SUMLEV,Geo_GEOCOMP,Geo_LOGRECNO,Geo_US,Geo_REGION,Geo_DIVISION,Geo_STATECE,Geo_STATE,Geo_COUNTY,Geo_COUSUB,Geo_PLACE,Geo_TRACT,Geo_BLKGRP,Geo_CONCIT,Geo_AIANHH,Geo_AIANHHFP,Geo_AIHHTLI,Geo_AITSCE,Geo_AITS,Geo_ANRC,Geo_CBSA,Geo_CSA,Geo_METDIV,Geo_MACC,Geo_MEMI,Geo_NECTA,Geo_CNECTA,Geo_NECTADIV,Geo_UA,Geo_UACP,Geo_CDCURR,Geo_SLDU,Geo_SLDL,Geo_VTD,Geo_ZCTA3,Geo_ZCTA5,Geo_SUBMCD,Geo_SDELM,Geo_SDSEC,Geo_SDUNI,Geo_UR,Geo_PCI,Geo_TAZ,Geo_UGA,Geo_PUMA5,Geo_PUMA1,Geo_GEOID,Geo_NAME,Geo_BTTR,Geo_BTBG,Geo_PLACESE,SE_A17005_001,SE_A17005_002,SE_A17005_003,PCT_SE_A17005_002,PCT_SE_A17005_003
0,42101000101,"Census Tract 1.01, Philadelphia County, Pennsy...",ACSSF,pa,140,0,8807,NaN,NaN,NaN,NaN,42,101,NaN,NaN,101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14000US42101000101,Census Tract 1.01,NaN,NaN,NaN,1675,1590,85,94.93,5.07
1,42101000102,"Census Tract 1.02, Philadelphia County, Pennsy...",ACSSF,pa,140,0,8808,NaN,NaN,NaN,NaN,42,101,NaN,NaN,102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14000US42101000102,Census Tract 1.02,NaN,NaN,NaN,2246,2152,94,95.81,4.19
2,42101000200,"Census Tract 2, Philadelphia County, Pennsylvania",ACSSF,pa,140,0,8809,NaN,NaN,NaN,NaN,42,101,NaN,NaN,200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14000US42101000200,Census Tract 2,NaN,NaN,NaN,2361,2236,125,94.71,5.29
3,42101000300,"Census Tract 3, Philadelphia County, Pennsylvania",ACSSF,pa,140,0,8810,NaN,NaN,NaN,NaN,42,101,NaN,NaN,300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14000US42101000300,Census Tract 3,NaN,NaN,NaN,2097,2004,93,95.57,4.43
4,42101000401,"Census Tract 4.01, Philadelphia County, Pennsy...",ACSSF,pa,140,0,8811,NaN,NaN,NaN,NaN,42,101,NaN,NaN,401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14000US42101000401,Census Tract 4.01,NaN,NaN,NaN,1630,1622,8,99.51,0.49